### ISSUE TITLE
basecalling.sh - Extracting raw reads into channel specific POD5s

### ISSUE THREAD

**Issue by akunln** [JWDebler/nanopore_kit14_assembly#2]
Hello,

why is the step "Extracting raw reads into channel specific POD5s"  necessary? Could not the POD5 files separated by barcode used as input for the duplex basecalling?

Thanks for your help.

**Comment by JWDebler** [comment]
It speeds up duplex basecalling by a lot. Have a look at the Dorado GitHub
page under "Improving the Speed of Duplex Basecalling"
