### ISSUE TITLE
split reads usage

### ISSUE THREAD

**Issue by LeilyR** [JWDebler/nanopore_kit14_assembly#3]
Hi,
Thanks for the script on how to demux the duplex data from dorado. May I ask you what the usage of split reads is? I am not sure I can see where and how you use them for the second basecalling.

**Comment by JWDebler** [comment]
Hi,
Split reads are a bit funny. They happen when Dorado finds a barcode inside
a read and then splits that read into two separate bam\fastq reads and
assigns new read IDs. Unfortunately it can't split the original pod5 read
though. So my script collects those split read fastqs and merges them later
on with the 'sup' called simplex reads before feeding them to the
'correction' module.

Hope this explains it.

**Comment by LeilyR** [comment]
Hi, Thank you so much for the respond. Did I understood you correctly, that these reads never get called with the duplex module?

**Comment by JWDebler** [comment]
Correct. Because those split reads after splitting don't have a
corresponding raw read in the POD5 file that can be duplex called. But
instead of throwing the data away I keep them and add them to the reads
that get corrected later.

**Comment by LeilyR** [comment]
I see. Thanks you so much!
